INSERT IGNORE INTO `wbm_data_layer_properties` (`id`, `parentID`, `name`,`module`, `value`) VALUES
(112,0,'name','frontend_index_index','{$sArticle.articleName|escape}'),
(114,28,'name','frontend_checkout_ajaxaddarticlecart','{dbquery select=''articlename'' from=''s_order_basket'' where=[''ordernumber ='' => $smarty.request.sAdd\, ''sessionID ='' => $smarty.session.Shopware.sessionId] order=[''id'' => ''DESC'']}'),
(115,28,'brand','frontend_checkout_ajaxaddarticlecart','{dbquery select=''name'' from=''s_articles_supplier'' where=[''id ='' => {dbquery select=''supplierID'' from=''s_articles'' where=[''id ='' => {dbquery select=''articleID'' from=''s_order_basket'' where=[''ordernumber ='' => $smarty.request.sAdd\, ''sessionID ='' => $smarty.session.Shopware.sessionId] order=[''id'' => ''DESC'']}]}]}'),
(116,37,'name','frontend_checkout_ajaxdeletearticlecart','{dbquery select=''articlename'' from=''s_order_basket'' where=[''id ='' => {request_get param=''sDelete''}]}'),
(117,37,'brand','frontend_checkout_ajaxdeletearticlecart','{dbquery select=''name'' from=''s_articles_supplier'' where=[''id ='' => {dbquery select=''supplierID'' from=''s_articles'' where=[''id ='' => {dbquery select=''articleID'' from=''s_order_basket'' where=[''id ='' => {request_get param=''sDelete''}]}]}]}'),
(118,44,'category','frontend_checkout_cart','{dbquery select=''description'' from=''s_categories'' where=[''id ='' => {dbquery select=''categoryID'' from=''s_articles_categories'' where=[''articleID ='' => $sArticle.articleID]}]}'),
(119,56,'category','frontend_checkout_confirm','{dbquery select=''description'' from=''s_categories'' where=[''id ='' => {dbquery select=''categoryID'' from=''s_articles_categories'' where=[''articleID ='' => $sArticle.articleID]}]}'),
(120,68,'category','frontend_checkout_finish','{dbquery select=''description'' from=''s_categories'' where=[''id ='' => {dbquery select=''categoryID'' from=''s_articles_categories'' where=[''articleID ='' => $sArticle.articleID]}]}');
